# Note: Makefiles are technically native to Linux/Mac. 
# You can run these commands manually in Windows, or install 'make' via Chocolatey later.

build:
	pyinstaller suvi.spec --clean -y

run:
	python suvi/__main__.py

test:
	pytest tests/